Basketball/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('player/', include('playerstats.urls')),
    path('', include('mysite.urls')),
    path('', include('gamestats.urls')),
]

game/urls.py
from django.urls import path
from . import views


app_name = 'game'
template_dir = 'game/'

urlpatterns = [
    path('add/',
         views.GameCreate.as_view(template_name=template_dir + 'add.html'),
         name='add'),
]

gamestats/urls.py
from django.urls import path
from . import views


app_name = 'gamestats'
template_dir = 'gamestats/'

urlpatterns = [
    path('ranking/',
         views.GameStatsList.as_view(template_name=template_dir + 'ranking.html'),
         name='ranking'),
    path('schedule/',
         views.GameSchedule.as_view(template_name=template_dir + 'schedule.html'),
         name='schedule'),
]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'home'
template_dir = 'mysite/'

urlpatterns = [
    path('',
         views.Home.as_view(template_name=template_dir + 'home.html'),
         name='home'),
    path('teams/',
         views.TeamsList.as_view(template_name=template_dir + 'teams.html'),
         name='teams-list'),
    path('teams/<str:pk>/',
         views.TeamDetail.as_view(template_name=template_dir + 'team.html'),
         name='team-profile'),
    path('players/',
         views.PlayerList.as_view(template_name=template_dir + 'players.html'),
         name='players-list'),
    path('players/<int:pk>/',
         views.PlayerDetail.as_view(template_name=template_dir + 'player.html'),
         name='player-profile'),
]

mysite/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=40, primary_key=True)

    class Meta:
        db_table = 'team'

    def __str__(self):
        return f'{self.name}'


class Player(models.Model):
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    class Meta:
        db_table = 'player'

    def __str__(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}' \
               f' ({self.team.name})'

    def get_full_name(self):
        return f'{self.first_name} {self.middle_name} {self.last_name}'

mysite/views.py
from .models import Player
from game.models import Team
from gamestats.models import GameStats as GS
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView
)


class Home(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['games'] = GS \
            .get_game_schedule_with_score() \
            .to_dict('records')

        return context


class TeamDetail(DetailView):
    model = Team
    context_object_name = 'team'


class TeamsList(ListView):
    model = Team
    context_object_name = 'teams'


class PlayerDetail(DetailView):
    model = Player
    context_object_name = 'player'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        player = self.get_object()
        context['full_name'] = player.get_full_name()

        return context


class PlayerList(ListView):
    model = Player
    context_object_name = 'players'

templates/mysite/_header.html
<header class="header">
    <div class="container header__container">
        {% include 'mysite/_menu.html' %}
    </div>
</header>

templates/mysite/_menu.html
<nav class="menu">
    <ul class="menu__list">
        <li class="menu__item"><a href="{% url 'home:home' %}" class="menu__link">Home</a></li>
        <li class="menu__item"><a class="menu__link">Tabela</a>
            <ul class="menu__dropdown">
                <li class="menu__item"><a href="{% url 'gamestats:ranking' %}" class="menu__link">Drużyny</a></li>
                <li class="menu__item"><a href="{% url 'playerstats:player-ranking' %}" class="menu__link">Zawodnicy</a></li>
            </ul>
        </li>
        <li class="menu__item"><a class="menu__link">Statystyki</a>
            <ul class="menu__dropdown">
                <li class="menu__item"><a class="menu__link">Zawodnicy</a>
                    <ul class="menu__sublist">
                        <li class="menu__item"><a href="{% url 'playerstats:player-stats-add' %}"class="menu__link">Dodaj</a></li>
                        <li class="menu__item"><a class="menu__link">Edytuj</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="menu__item"><a class="menu__link">Mecze</a>
            <ul class="menu__dropdown">
                <li class="menu__item"><a href="{% url 'game:game-schedule' %}" class="menu__link">Terminarz</a></li>
                <li class="menu__item"><a href="{% url 'game:game-add' %}" class="menu__link">Dodaj</a></li>
            </ul>
        </li>
    </ul>
</nav>

templates/mysite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
{% include 'mysite/_header.html' %}
{% block content %}
{% endblock %}
</body>
</html>

templates/mysite/home.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
    <main class="main container">
        <div class="grid grid--home">
            <div class="card">
                <h1>Koszykówka</h1>
            </div>

            <div class="card">
                <h2>Terminarz</h2>
                <hr>
            </div>

            <div class="card">
                <h2>Lorem ipsum</h2>
                <hr>
            </div>

            {% include 'components/_game-schedule.html' with games=games %}
        </div>
    </main>
{% endblock %}

templates/mysite/player-rank.html
{% extends 'mysite/base.html' %}
{% block content %}
    <ul>
        {% for player in player_rank %}
            <li>{{ player }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/mysite/player.html
{% extends 'layout/base.html' %}
{% block content %}
    <main class="main container">
        <div class="card">
            <div class="profile">
                {% include 'components/_profile.html' with team=player.team name=full_name %}
                <div class="profile__body">
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/mysite/players.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
    <main class="main container">
        <div class="card card--100">
            <header class="card__header">
                <h1>Lista zawodników</h1>
                <hr>
            </header>
            <section class="card__body">
                <ul class="ul">
                    {% for player in players %}
                        <li class="ul__item">
                            <a class="link" href="{% url 'home:player-profile' player.pk %}">
                                <figure class="poster">
                                    <img class="poster__img poster__img--small" src="{% static 'img/default-profile-picture.png' %}" alt="Profile picture">
                                    <figcaption class="poster__caption">
                                        <p class="poster__name">{{ player.first_name }} {{ player.last_name }}</p>
                                        <p class="poster__team">({{ player.team }})</p>
                                    </figcaption>
                                </figure>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </main>
{% endblock %}

templates/mysite/team.html
{% extends 'layout/base.html' %}
{% block content %}
    <main class="main container">
        <div class="card">
            <div class="profile">
                {% include 'components/_profile.html' with name=team.name team=None picture_path='img/default-team-profile-picture.png' %}
                <div class="profile__body">
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/mysite/teams.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}
    <main class="main container">
        <div class="card card--100">
            <header class="card__header">
                <h1>Wszystkie drużyny</h1>
                <hr>
            </header>
            <section class="card__body">
                <ul class="ul">
                    {% for team in teams %}
                        <li class="ul__item">
                            <a class="link" href="{% url 'home:team-profile' team.pk %}">
                                <figure class="poster">
                                    <img class="poster__img poster__img--small" src="{% static 'img/default-team-profile-picture.png' %}" alt="Profile picture">
                                    <figcaption class="poster__caption">
                                        <p class="poster__name">{{ team.name }}</p>
                                    </figcaption>
                                </figure>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </main>
{% endblock %}