Basketball/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('player/', include('playerstats.urls')),
    path('', include('mysite.urls')),
    path('', include('gamestats.urls')),
]

game/urls.py
from django.urls import path
from . import views


app_name = 'game'
template_dir = 'game/'

urlpatterns = [
    path('add/',
         views.GameCreate.as_view(template_name=template_dir + 'add.html'),
         name='add'),
]

game/forms.py
from django import forms
from .models import Season


class SeasonSearchForm(forms.ModelForm):
    """
    Contains all available seasons.
    """
    seasons = Season.objects.values_list('year')
    seasons_tuple = [season + season for season in seasons]
    seasons_tuple.insert(0, ('Wszystkie', 'Wszystkie'))  # All seasons

    year = forms.ChoiceField(choices=seasons_tuple)

    class Meta:
        model = Season
        fields = ['year']

templates/components/_game-schedule.html
<table class="table">
    <thead class="table__head">
    <tr>
        <th class="table__header">Data</th>
        <th class="table__header">Drużyna 1</th>
        <th class="table__header">Wynik</th>
        <th class="table__header">Drużyna 2</th>
        <th class="table__header">Walkower</th>
    </tr>
    </thead>
    <tbody>
    {% for game in games %}
        <tr class="table__row">
            <td class="table__cell">{{ game.date|date:"d/m/Y" }}</td>
            <td class="table__cell">{{ game.team_1 }}</td>
            <td class="table__cell">
                {% if game.forfeit is None %}
                    {{ game.score }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td class="table__cell">{{ game.team_2 }}</td>
            <td class="table__cell">
                {% if game.forfeit %}
                    {{ game.forfeit }}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/components/_pagination.html
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?page=1">
            <button class="btn">Pierwsza</button>
        </a>
        <a href="?page={{ page_obj.previous_page_number }}">
            <button class="btn">Poprzednia</button>
        </a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a href="?page={{ num }}">
                <button class="btn">{{ num }}</button>
            </a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">
                <button class="btn">{{ num }}</button>
            </a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">
            <button class="btn">Następna</button>
        </a>
        <a href="?page={{ page_obj.paginator.num_pages }}">
            <button class="btn">Ostatnia</button>
        </a>
    {% endif %}
</div>

templates/components/_profile.html
{% load static %}
<header class="profile__header">
    <figure class="poster">
        <img class="poster__img" src="{% static picture_path %}" alt="Profile picture">
{#        <img class="poster__img" src="{% static 'img/default-profile-picture.png' %}" alt="Profile picture">#}
    </figure>
    <div class="profile__personal">
        <h1 class="profile__name">{{ name }}</h1>
        {% if team %}
            <h2 class="profile__team">{{ team }}</h2>
        {% endif %}
        <hr>
    </div>
</header>

templates/components/_statistics_form.html
<form method="post" class="form" id="add-stats">
    {% csrf_token %}
    <div class="form__card">
        <fieldset class="form__fieldset">
            <div class="form__row">
                <label for="id_year">Sezon: </label>
                {{ seasons.year }}
            </div>
            <div class="form__row">
                {{ form.game.label_tag }}
                {{ form.game }}
            </div>
            <div class="form__row">
                {{ form.player.label_tag }}
                {{ form.player }}
            </div>
        </fieldset>
    </div>
    <div class="form__card">
        <fieldset class="form__fieldset">
            <legend class="form__legend">Rzuty</legend>
            <hr>
            <div class="form__row">
                {{ form.shot_1_pts_ok.label_tag }}
                {{ form.shot_1_pts_ok }}
            </div>
            <div class="form__row">
                {{ form.shot_1_pts_total.label_tag }}
                {{ form.shot_1_pts_total }}
            </div>
            <div class="form__row">
                {{ form.shot_2_pts_ok.label_tag }}
                {{ form.shot_2_pts_ok }}
            </div>
            <div class="form__row">
                {{ form.shot_2_pts_total.label_tag }}
                {{ form.shot_2_pts_total }}
            </div>
            <div class="form__row">
                {{ form.shot_3_pts_ok.label_tag }}
                {{ form.shot_3_pts_ok }}
            </div>
            <div class="form__row">
                {{ form.shot_3_pts_total.label_tag }}
                {{ form.shot_3_pts_total }}
            </div>
        </fieldset>
        <fieldset class="form__fieldset">
            <legend class="form__legend">Zbiórki</legend>
            <hr>
            <div class="form__row">
                {{ form.reb_def.label_tag }}
                {{ form.reb_def }}
            </div>
            <div class="form__row">
                {{ form.reb_off.label_tag }}
                {{ form.reb_off }}
            </div>
        </fieldset>
        <fieldset class="form__fieldset">
            <legend class="form__legend">Faule</legend>
            <hr>
            <div class="form__row">
                {{ form.foul_def.label_tag }}
                {{ form.foul_def }}
            </div>
            <div class="form__row">
                {{ form.foul_off.label_tag }}
                {{ form.foul_off }}
            </div>
            <div class="form__row">
                {{ form.foul_unsport.label_tag }}
                {{ form.foul_unsport }}
            </div>
            <div class="form__row">
                {{ form.foul_tech.label_tag }}
                {{ form.foul_tech }}
            </div>
            <div class="form__row">
                {{ form.foul_disq.label_tag }}
                {{ form.foul_disq }}
            </div>
        </fieldset>
        <fieldset class="form__fieldset">
            <legend class="form__legend">Pozostałe statystyki</legend>
            <hr>
            <div class="form__row">
                {{ form.ast.label_tag }}
                {{ form.ast }}
            </div>
            <div class="form__row">
                {{ form.stl.label_tag }}
                {{ form.stl }}
            </div>
            <div class="form__row">
                {{ form.blck.label_tag }}
                {{ form.blck }}
            </div>
            <div class="form__row">
                {{ form.ball_loos.label_tag }}
                {{ form.ball_loos }}
            </div>
            <div class="form__row">
                {{ form.time.label_tag }}
                {{ form.time }}
            </div>
        </fieldset>
        <div class="form__row">
            <button class="btn form__btn" type="submit">
                {{ btn_message|default:"Dodaj" }}
            </button>
        </div>
    </div>
</form>

templates/components/_statistics_legend.html
<dl class="dl">
    {% for meta_info in legend.values %}
        <div class="dl__cell">
            <dt class="dl__term">{{ meta_info.verbose_name }}</dt>
            <dd class="dl__description">{{ meta_info.help_text }}</dd>
        </div>
    {% endfor %}
</dl>

templates/components/_table-description-card.html
<div class="card">
    <header class="card__header">
        <h1>Ranking {{ type }} <span id="current-season-choice"></span></h1>
        <hr>
    </header>
    <section class="card__body">
        <form action="{% url season_redirect %}">
            <label>Sezon:
                <select name="season" id="season" onchange="this.form.submit()">
                    {% for value, text in form.year.field.choices %}
                        <option value="{{ value }}" {% if request.GET.season|add:"0" == value|add:"0" %}selected{% endif %}>
                            {{ value }}
                        </option>
                    {% endfor %}
                </select>
            </label>
        </form>

        <h2>Legenda</h2>
        {% include 'components/_statistics_legend.html' with legend=legend %}
    </section>
</div>

templates/components/_table-ranking.html
<table class="table">
    <thead class="table__head">
    <tr>
        {% for header in ranking.0 %}
            <th class="table__header">{{ header }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for row in ranking %}
        <tr class="table__row">
            {% for thead, value in row.items %}
                <td class="table__cell">{{ value }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>