Basketball/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('player/', include('playerstats.urls')),
    path('', include('mysite.urls')),
    path('', include('gamestats.urls')),
]

game/urls.py
from django.urls import path
from . import views


app_name = 'game'
template_dir = 'game/'

urlpatterns = [
    path('add/',
         views.GameCreate.as_view(template_name=template_dir + 'add.html'),
         name='add'),
]

gamestats/urls.py
from django.urls import path
from . import views


app_name = 'gamestats'
template_dir = 'gamestats/'

urlpatterns = [
    path('ranking/',
         views.GameStatsList.as_view(template_name=template_dir + 'ranking.html'),
         name='ranking'),
    path('schedule/',
         views.GameSchedule.as_view(template_name=template_dir + 'schedule.html'),
         name='schedule'),
]

mysite/urls.py
from django.urls import path
from . import views

app_name = 'home'
template_dir = 'mysite/'

urlpatterns = [
    path('',
         views.Home.as_view(template_name=template_dir + 'home.html'),
         name='home'),
    path('teams/',
         views.TeamsList.as_view(template_name=template_dir + 'teams.html'),
         name='teams-list'),
    path('teams/<str:pk>/',
         views.TeamDetail.as_view(template_name=template_dir + 'team.html'),
         name='team-profile'),
    path('players/',
         views.PlayerList.as_view(template_name=template_dir + 'players.html'),
         name='players-list'),
    path('players/<int:pk>/',
         views.PlayerDetail.as_view(template_name=template_dir + 'player.html'),
         name='player-profile'),
]

playerstats/urls.py
from django.urls import path
from . import views


app_name = 'playerstats'
template_dir = 'playerstats/'

urlpatterns = [
    path('statistics/add/',
         views.PlayerStatsCreate.as_view(
             template_name=template_dir + 'add.html'
         ),
         name='add'),
    path('statistics/list/',
         views.PlayerStatsList.as_view(
             template_name=template_dir + 'list.html'
         ),
         name='list'),
    path('statistics/<int:pk>/update/',
         views.PlayerStatsUpdate.as_view(
             template_name=template_dir + 'add.html'
         ),
         name='update'),
    path('ranking/',
         views.PlayerStatsRanking.as_view(
             template_name=template_dir + 'ranking.html'
         ),
         name='ranking'),
]

templates/layout/_header.html
<header class="header">
    <div class="container header__container">
        {% include 'layout/_menu.html' %}
    </div>
</header>

templates/layout/_menu.html
{% load static %}
<nav class="menu">
    <ul class="menu__list">
        <li class="menu__item">
            <a href="{% url 'home:home' %}" class="menu__link">Home
                <span class="menu__icon">
                    <i class="icon-home"></i>
                </span>
            </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'home:teams-list' %}" class="menu__link">Drużyny
                <span class="menu__icon">
                    <i class="icon-group"></i>
                </span>
            </a>
        </li>
        <li class="menu__item">
            <a href="{% url 'home:players-list' %}" class="menu__link">Zawodnicy
                <span class="menu__icon">
                    <i class="icon-adult"></i>
                </span>
            </a>
        </li>
        <li class="menu__item"><a class="menu__link">Tabela
            <span class="menu__icon">
                    <i class="icon-trophy"></i>
            </span>
        </a>
            <ul class="menu__dropdown">
                <li class="menu__item">
                    <a href="{% url 'gamestats:ranking' %}" class="menu__link">Drużyny</a></li>
                <li class="menu__item"><a href="{% url 'playerstats:ranking' %}" class="menu__link">Zawodnicy</a></li>
            </ul>
        </li>
        <li class="menu__item">
            <a class="menu__link">Statystyki
                <span class="menu__icon">
                    <i class="icon-chart-bar"></i>
                </span>
            </a>
            <ul class="menu__dropdown">
                <li class="menu__item"><a class="menu__link">Zawodnicy</a>
                    <ul class="menu__sublist">
                        <li class="menu__item"><a href="{% url 'playerstats:add' %}" class="menu__link">Dodaj</a></li>
                        <li class="menu__item"><a href="{% url 'playerstats:list' %}" class="menu__link">Lista</a></li>
                        <li class="menu__item"><a class="menu__link">Edytuj</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="menu__item">
            <a class="menu__link">Mecze
                <span class="menu__icon">
                    <i class="icon-basketball"></i>
                </span>
            </a>
            <ul class="menu__dropdown">
                <li class="menu__item"><a href="{% url 'gamestats:schedule' %}" class="menu__link">Terminarz</a></li>
                <li class="menu__item"><a href="{% url 'game:add' %}" class="menu__link">Dodaj</a></li>
            </ul>
        </li>
    </ul>
</nav>

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <meta charset="UTF-8">
    <title>Koszykówka</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'fontello/css/fontello.css' %}">
</head>
<body>
{% include 'layout/_header.html' %}
<div class="bg">
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>